# Generated by Django 5.2.16 on 2026-07-12 11:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', '准备材料'), ('applied', '已投递'), ('screening', '简历筛选'), ('assessment', '笔试或测评'), ('interviewing', '面试中'), ('offer', '已收到 Offer'), ('accepted', '已接受 Offer'), ('rejected', '被拒绝'), ('withdrawn', '主动撤回'), ('ghosted', '长期未回复'), ('closed', '流程结束')], default='preparing', max_length=20, verbose_name='状态')),
                ('applied_at', models.DateField(blank=True, null=True, verbose_name='投递日期')),
                ('source', models.CharField(choices=[('company_website', '公司官网'), ('job_board', '招聘平台'), ('referral', '内推'), ('recruiter', '猎头或招聘人员'), ('campus', '校园招聘'), ('social_media', '社交媒体'), ('other', '其他')], default='other', max_length=20, verbose_name='投递来源')),
                ('source_detail', models.CharField(blank=True, max_length=200, verbose_name='来源说明')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('dream', '梦想公司')], default='medium', max_length=10, verbose_name='优先级')),
                ('next_action', models.CharField(blank=True, max_length=300, verbose_name='下一步行动')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='下次跟进日期')),
                ('last_contact_at', models.DateField(blank=True, null=True, verbose_name='最近联系日期')),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='期望薪资')),
                ('expected_salary_currency', models.CharField(default='JPY', max_length=3, verbose_name='期望薪资币种')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('withdrawn_reason', models.TextField(blank=True, verbose_name='撤回原因')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='被拒原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='companies.jobposition', verbose_name='职位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '投递',
                'verbose_name_plural': '投递',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('preparing', '准备材料'), ('applied', '已投递'), ('screening', '简历筛选'), ('assessment', '笔试或测评'), ('interviewing', '面试中'), ('offer', '已收到 Offer'), ('accepted', '已接受 Offer'), ('rejected', '被拒绝'), ('withdrawn', '主动撤回'), ('ghosted', '长期未回复'), ('closed', '流程结束')], max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('preparing', '准备材料'), ('applied', '已投递'), ('screening', '简历筛选'), ('assessment', '笔试或测评'), ('interviewing', '面试中'), ('offer', '已收到 Offer'), ('accepted', '已接受 Offer'), ('rejected', '被拒绝'), ('withdrawn', '主动撤回'), ('ghosted', '长期未回复'), ('closed', '流程结束')], max_length=20, verbose_name='新状态')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='applications.application', verbose_name='投递')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '投递状态记录',
                'verbose_name_plural': '投递状态记录',
                'ordering': ('-changed_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='面试轮次')),
                ('title', models.CharField(max_length=200, verbose_name='面试名称')),
                ('interview_type', models.CharField(choices=[('phone', '电话面试'), ('video', '视频面试'), ('onsite', '现场面试'), ('technical', '技术面试'), ('behavioral', '行为面试'), ('hr', 'HR 面试'), ('case_study', '案例分析'), ('other', '其他')], default='video', max_length=20, verbose_name='面试类型')),
                ('status', models.CharField(choices=[('scheduled', '已安排'), ('completed', '已完成'), ('cancelled', '已取消'), ('rescheduled', '已改期'), ('no_show', '未出席')], default='scheduled', max_length=20, verbose_name='状态')),
                ('scheduled_at', models.DateTimeField(verbose_name='面试时间')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='预计时长（分钟）')),
                ('meeting_url', models.URLField(blank=True, max_length=1000, verbose_name='会议链接')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='面试地点')),
                ('interviewer_names', models.CharField(blank=True, max_length=500, verbose_name='面试官')),
                ('preparation_notes', models.TextField(blank=True, verbose_name='准备笔记')),
                ('questions', models.TextField(blank=True, verbose_name='面试问题')),
                ('reflection', models.TextField(blank=True, verbose_name='面试复盘')),
                ('result', models.CharField(choices=[('pending', '等待结果'), ('passed', '通过'), ('failed', '未通过'), ('unknown', '未知')], default='pending', max_length=10, verbose_name='结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application', verbose_name='投递')),
            ],
            options={
                'verbose_name': '面试',
                'verbose_name_plural': '面试',
                'ordering': ('scheduled_at', 'round_number'),
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'status'], name='app_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'next_action_date'], name='app_user_next_action_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job_position'], name='app_job_position_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationstatuslog',
            index=models.Index(fields=['application', 'changed_at'], name='app_status_timeline_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status', 'scheduled_at'], name='interview_schedule_idx'),
        ),
        migrations.AddConstraint(
            model_name='interview',
            constraint=models.UniqueConstraint(fields=('application', 'round_number'), name='unique_interview_round_per_application'),
        ),
    ]
