# Generated by Django 5.2.16 on 2026-07-24 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('status', models.CharField(choices=[('todo', '未开始'), ('in_progress', '进行中'), ('done', '已完成'), ('blocked', '受阻')], default='todo', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='优先级')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('notes', models.TextField(blank=True, verbose_name='说明')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', 'due_at', '-updated_at'),
                'indexes': [models.Index(fields=['user', 'status', 'due_at'], name='todo_user_status_due_idx')],
            },
        ),
    ]
