# Generated by Django 5.2.16 on 2026-07-25 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_alter_aitask_status'),
        ('core', '0003_calendarevent'),
        ('mailboxes', '0004_emailaccount_sync_folder_syncedemail_folder_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostAgentHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(default='windows-local', max_length=100, unique=True)),
                ('version', models.CharField(blank=True, max_length=30)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('outlook_available', models.BooleanField(default=False)),
                ('ollama_available', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostAgentCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('outlook_connect', 'Outlook 连接'), ('outlook_sync', 'Outlook 同步'), ('ollama', '本地 Ollama 推理')], max_length=30)),
                ('status', models.CharField(choices=[('queued', '等待本机代理'), ('running', '本机代理处理中'), ('succeeded', '已完成'), ('failed', '失败'), ('expired', '已过期')], default='queued', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_agent_command', to='ai_assistant.aitask')),
                ('email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_agent_commands', to='mailboxes.emailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_agent_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='host_agent_queue_idx')],
            },
        ),
    ]
