# Generated by Django 5.2.16 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


def backfill_company_relations(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    TodoItem = apps.get_model('core', 'TodoItem')
    CalendarEvent = apps.get_model('core', 'CalendarEvent')

    buckets = {}

    def other_company(user_id):
        if user_id not in buckets:
            company, _ = Company.objects.get_or_create(
                user_id=user_id,
                name='其他事项',
                defaults={
                    'status': 'researching',
                    'priority': 'low',
                    'notes': '系统用于归类未关联公司的日程和 To Do。',
                },
            )
            buckets[user_id] = company.pk
        return buckets[user_id]

    for todo in TodoItem.objects.filter(company__isnull=True).iterator():
        todo.company_id = other_company(todo.user_id)
        todo.save(update_fields=('company',))

    events = CalendarEvent.objects.filter(company__isnull=True).select_related(
        'application__job_position', 'contact', 'source_email'
    )
    for event in events.iterator():
        company_id = None
        if event.application_id:
            company_id = event.application.job_position.company_id
        if not company_id and event.contact_id:
            company_id = event.contact.company_id
        if not company_id and event.source_email_id:
            company_id = event.source_email.company_id
        event.company_id = company_id or other_company(event.user_id)
        event.save(update_fields=('company',))


class Migration(migrations.Migration):
    dependencies = [
        ('applications', '0003_application_resume'),
        ('companies', '0004_company_pinned_order'),
        ('core', '0004_hostagentheartbeat_hostagentcommand'),
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='company',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='todo_items',
                to='companies.company',
                verbose_name='公司',
            ),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='job_position',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='todo_items',
                to='companies.jobposition',
                verbose_name='关联职位',
            ),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='application',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='todo_items',
                to='applications.application',
                verbose_name='关联投递',
            ),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='job_position',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='calendar_events',
                to='companies.jobposition',
            ),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('call', '电话/视频沟通'),
                    ('assessment', '笔试/测评'),
                    ('briefing', '说明会'),
                    ('es_deadline', 'ES 截止'),
                    ('interview', '面试'),
                    ('other', '其他日程'),
                ],
                default='other',
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_company_relations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='todoitem',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='todo_items',
                to='companies.company',
                verbose_name='公司',
            ),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='calendar_events',
                to='companies.company',
            ),
        ),
    ]
