# Generated by Django 5.2.16 on 2026-07-12 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='显示名称')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='所在地')),
                ('timezone', models.CharField(default='Asia/Tokyo', max_length=64, verbose_name='时区')),
                ('target_role', models.CharField(blank=True, max_length=200, verbose_name='目标职位')),
                ('default_currency', models.CharField(default='JPY', max_length=3, verbose_name='默认币种')),
                ('email_reminders', models.BooleanField(default=True, verbose_name='接收邮件提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
