# Generated by Django 5.2.16 on 2026-07-12 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_jobposition_ai_metadata'),
        ('productivity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_provider', models.CharField(choices=[('ollama', '本地 Ollama'), ('openai', 'OpenAI API')], default='ollama', max_length=20)),
                ('ollama_url', models.URLField(default='http://127.0.0.1:11434')),
                ('ollama_model', models.CharField(default='qwen3:8b', max_length=100)),
                ('encrypted_openai_api_key', models.TextField(blank=True)),
                ('openai_key_suffix', models.CharField(blank=True, max_length=4)),
                ('openai_key_verified', models.BooleanField(default=False)),
                ('allow_sensitive_cloud', models.BooleanField(default=False)),
                ('openai_fast_model', models.CharField(default='gpt-5.6-luna', max_length=100)),
                ('openai_quality_model', models.CharField(default='gpt-5.6-terra', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('jd_parse', 'JD 结构化解析'), ('job_match', '简历职位匹配')], max_length=20)),
                ('provider', models.CharField(choices=[('ollama', '本地 Ollama'), ('openai', 'OpenAI API')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('running', '处理中'), ('succeeded', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('prompt_version', models.CharField(default='v1', max_length=30)),
                ('input_payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('sensitive_cloud_consent', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='companies.jobposition')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_tasks', to='productivity.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIMatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('summary', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_match_analyses', to='companies.jobposition')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_match_analyses', to='productivity.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_match_analyses', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_analysis', to='ai_assistant.aitask')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['user', 'status', 'created_at'], name='ai_task_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['job', 'task_type', 'created_at'], name='ai_task_job_type_idx'),
        ),
    ]
