# Generated by Django 5.2.16 on 2026-07-25 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('applications', '0003_application_resume'),
        ('companies', '0003_jobposition_ai_metadata'),
        ('mailboxes', '0004_emailaccount_sync_folder_syncedemail_folder_name_and_more'),
        ('productivity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailScheduleCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('needs_info', '需要补充'), ('approved', '已加入日程'), ('rejected', '已忽略')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('interview', '面试'), ('call', '电话/视频沟通'), ('assessment', '笔试/测评'), ('briefing', '说明会'), ('follow_up', '跟进事项'), ('other', '其他')], default='other', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('timezone_name', models.CharField(default='Asia/Tokyo', max_length=64)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('meeting_url', models.URLField(blank=True, max_length=1000)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0)),
                ('created_object_type', models.CharField(blank=True, max_length=30)),
                ('created_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='aisettings',
            name='email_schedule_auto_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='email_schedule_auto_limit',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='aitask',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='mailboxes.syncedemail'),
        ),
        migrations.AlterField(
            model_name='aitask',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to='companies.jobposition'),
        ),
        migrations.AlterField(
            model_name='aitask',
            name='task_type',
            field=models.CharField(choices=[('jd_parse', 'JD 结构化解析'), ('job_match', '简历职位匹配'), ('email_schedule', '邮件日程提取')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='aitask',
            index=models.Index(fields=['email', 'task_type', 'created_at'], name='ai_task_email_type_idx'),
        ),
        migrations.AddField(
            model_name='emailschedulecandidate',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_schedule_candidates', to='applications.application'),
        ),
        migrations.AddField(
            model_name='emailschedulecandidate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_schedule_candidates', to='companies.company'),
        ),
        migrations.AddField(
            model_name='emailschedulecandidate',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_schedule_candidates', to='productivity.contact'),
        ),
        migrations.AddField(
            model_name='emailschedulecandidate',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_candidates', to='mailboxes.syncedemail'),
        ),
        migrations.AddField(
            model_name='emailschedulecandidate',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_candidates', to='ai_assistant.aitask'),
        ),
        migrations.AddField(
            model_name='emailschedulecandidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_schedule_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailschedulecandidate',
            index=models.Index(fields=['user', 'status', 'starts_at'], name='email_schedule_review_idx'),
        ),
    ]
