# Generated by Django 5.2.16 on 2026-07-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_emailschedulecandidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitask',
            name='status',
            field=models.CharField(choices=[('pending', '等待处理'), ('waiting_host', '等待本机代理'), ('running', '处理中'), ('succeeded', '已完成'), ('failed', '失败')], default='pending', max_length=20),
        ),
    ]
