# Generated by Django 5.2.16 on 2026-07-12 11:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('status', models.CharField(choices=[('researching', '调研中'), ('watching', '持续关注'), ('target', '目标公司'), ('active', '正在接触'), ('paused', '暂停关注'), ('rejected', '暂不考虑'), ('archived', '已归档')], default='researching', max_length=20, verbose_name='状态')),
                ('website_url', models.URLField(blank=True, max_length=500, verbose_name='公司官网')),
                ('careers_url', models.URLField(blank=True, max_length=500, verbose_name='招聘官网')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='所在地')),
                ('company_size', models.CharField(blank=True, max_length=100, verbose_name='公司规模')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('dream', '梦想公司')], default='medium', max_length=10, verbose_name='优先级')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'ordering': ('-updated_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='职位名称')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='部门')),
                ('status', models.CharField(choices=[('draft', '待整理'), ('open', '招聘中'), ('closed', '已关闭'), ('expired', '已过期'), ('filled', '已招满'), ('unknown', '未知')], default='open', max_length=10, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='职位描述')),
                ('requirements', models.TextField(blank=True, verbose_name='任职要求')),
                ('benefits', models.TextField(blank=True, verbose_name='福利待遇')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='职位链接')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='投递截止日期')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='工作地点')),
                ('work_mode', models.CharField(choices=[('onsite', '现场办公'), ('hybrid', '混合办公'), ('remote', '远程办公'), ('unknown', '未说明')], default='unknown', max_length=10, verbose_name='办公方式')),
                ('employment_type', models.CharField(choices=[('full_time', '全职'), ('part_time', '兼职'), ('contract', '合同工'), ('internship', '实习'), ('temporary', '临时'), ('other', '其他')], default='full_time', max_length=20, verbose_name='雇佣类型')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最低薪资')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='最高薪资')),
                ('salary_currency', models.CharField(default='JPY', max_length=3, verbose_name='薪资币种')),
                ('salary_period', models.CharField(choices=[('hourly', '时薪'), ('monthly', '月薪'), ('yearly', '年薪')], default='yearly', max_length=10, verbose_name='薪资周期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_positions', to='companies.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'ordering': ('application_deadline', '-updated_at'),
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['user', 'status'], name='company_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['user', 'priority'], name='company_user_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_company_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['company', 'status'], name='job_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposition',
            index=models.Index(fields=['application_deadline'], name='job_deadline_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobposition',
            constraint=models.CheckConstraint(condition=models.Q(('salary_min__isnull', True), ('salary_max__isnull', True), ('salary_min__lte', models.F('salary_max')), _connector='OR'), name='job_salary_min_lte_max'),
        ),
    ]
