# Generated by Django 5.2.16 on 2026-07-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='category',
            field=models.CharField(choices=[('technical', '技术职'), ('general', '综合职'), ('consulting', '咨询职'), ('sales', '营业职'), ('planning', '企划／运营职'), ('design', '设计职'), ('other', '其他')], default='technical', max_length=20, verbose_name='职位类别'),
        ),
        migrations.AddField(
            model_name='jobposition',
            name='category_other',
            field=models.CharField(blank=True, help_text='选择“其他”时填写。', max_length=100, verbose_name='其他职位类别'),
        ),
    ]
