# Generated by Django 5.2.16 on 2026-07-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_jobposition_category_jobposition_category_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposition',
            name='ai_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='AI 结构化元数据'),
        ),
    ]
