# Generated by Django 5.2.16 on 2026-08-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('companies', '0003_jobposition_ai_metadata')]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pinned_order',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='留空时按最近行动时间自动排序。',
                null=True,
                verbose_name='首页置顶顺序',
            ),
        ),
    ]
