# Generated by Django 5.2.16 on 2026-07-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailboxes', '0001_initial'),
        ('productivity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncedemail',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_emails', to='productivity.contact'),
        ),
        migrations.AddConstraint(
            model_name='emailaccount',
            constraint=models.UniqueConstraint(fields=('user', 'provider', 'email_address'), name='unique_user_email_provider'),
        ),
        migrations.AddConstraint(
            model_name='syncedemail',
            constraint=models.UniqueConstraint(fields=('account', 'provider_message_id'), name='unique_provider_message'),
        ),
    ]
