# Generated by Django 5.2.16 on 2026-07-12 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0003_alter_emailaccount_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='sync_folder',
            field=models.CharField(default='Inbox', max_length=255),
        ),
        migrations.AddField(
            model_name='syncedemail',
            name='folder_name',
            field=models.CharField(default='Inbox', max_length=255),
        ),
        migrations.AddField(
            model_name='syncedemail',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syncedemail',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DeletedEmailMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_markers', to='mailboxes.emailaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='deleted_email_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'message_hash'), name='unique_deleted_email_marker')],
            },
        ),
    ]
